services:
  mysql-db:
    image: mysql:9.4.0
    container_name: mysql-db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: projet3
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql-data:
